version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: MiPass123
      MYSQL_DATABASE: appdb        # crea la BD si no existe
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d:ro
    ports:
      - '3310:3306'
    networks:
      - app-net

  backend:
    image: hernans87/todo-backend:1.0
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: MiPass123
      DB_NAME: appdb
    ports:
      - '3000:3000'
    networks:
      - app-net

  frontend:
    image: hernans87/todo-frontend:1.0
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '4200:80'
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
